spring.application.name=ecommerce
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
currency.api.url=https://v6.exchangerate-api.com/v6
currency.api.key=3f2cc5756bd4358e73d5f248
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect